-- Dashboard Marketing — Push Notification V13
-- 2026-09-02
-- Adds per-device Web Push subscriptions and dispatch outbox.
-- Every modern Bell notification and every legacy central-business Bell
-- notification is mirrored into the push outbox.

begin;

do $$
begin
  if to_regclass('public.profiles') is null then
    raise exception 'Table public.profiles tidak ditemukan';
  end if;

  if to_regclass('public.notifications') is null then
    raise exception 'Table public.notifications tidak ditemukan';
  end if;

  if to_regclass('public.central_business_entities') is null then
    raise exception 'Table public.central_business_entities tidak ditemukan';
  end if;
end
$$;

create table if not exists public.push_subscriptions_v13 (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null
    references public.profiles(id)
    on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_key text not null,
  user_agent text null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  disabled_at timestamptz null
);

create index if not exists idx_push_subscriptions_v13_profile_enabled
  on public.push_subscriptions_v13(profile_id, enabled);

alter table public.push_subscriptions_v13
  enable row level security;

revoke all
  on public.push_subscriptions_v13
  from anon, authenticated;

grant select, insert, update, delete
  on public.push_subscriptions_v13
  to service_role;

create table if not exists public.push_dispatch_config_v13 (
  singleton boolean primary key default true
    check (singleton = true),
  vapid_public_key text null,
  dispatch_url text null,
  dispatch_key text null,
  updated_at timestamptz not null default now()
);

insert into public.push_dispatch_config_v13(singleton)
values (true)
on conflict (singleton) do nothing;

alter table public.push_dispatch_config_v13
  enable row level security;

revoke all
  on public.push_dispatch_config_v13
  from anon, authenticated;

grant select, update
  on public.push_dispatch_config_v13
  to service_role;

create table if not exists public.push_outbox_v13 (
  id bigint generated by default as identity primary key,
  source text not null,
  source_id text not null,
  recipient_profile_id uuid not null
    references public.profiles(id)
    on delete cascade,
  notification_type text null,
  module text null,
  title text not null,
  message text not null,
  link_path text null,
  status text not null default 'PENDING'
    check (
      status in (
        'PENDING',
        'PROCESSING',
        'SENT',
        'NO_SUBSCRIPTION',
        'FAILED'
      )
    ),
  attempts integer not null default 0,
  created_at timestamptz not null default now(),
  sent_at timestamptz null,
  last_error text null,
  unique (source, source_id, recipient_profile_id)
);

create index if not exists idx_push_outbox_v13_status_created
  on public.push_outbox_v13(status, created_at);

alter table public.push_outbox_v13
  enable row level security;

revoke all
  on public.push_outbox_v13
  from anon, authenticated;

grant select, update
  on public.push_outbox_v13
  to service_role;

grant usage, select
  on sequence public.push_outbox_v13_id_seq
  to service_role;

create or replace function public.get_push_vapid_public_key_v13()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select nullif(trim(vapid_public_key), '')
  from public.push_dispatch_config_v13
  where singleton = true;
$$;

revoke all
  on function public.get_push_vapid_public_key_v13()
  from public;

grant execute
  on function public.get_push_vapid_public_key_v13()
  to authenticated;

create or replace function public.register_push_subscription_v13(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
  v_endpoint text;
  v_p256dh text;
  v_auth text;
begin
  v_profile_id := public.current_profile_id();
  v_endpoint := trim(coalesce(p_endpoint, ''));
  v_p256dh := trim(coalesce(p_p256dh, ''));
  v_auth := trim(coalesce(p_auth, ''));

  if v_profile_id is null then
    raise exception 'Profile aktif untuk user login tidak ditemukan.';
  end if;

  if length(v_endpoint) < 20 then
    raise exception 'Push endpoint tidak valid.';
  end if;

  if length(v_p256dh) < 10 or length(v_auth) < 5 then
    raise exception 'Push subscription key tidak valid.';
  end if;

  insert into public.push_subscriptions_v13 (
    profile_id,
    endpoint,
    p256dh,
    auth_key,
    user_agent,
    enabled,
    updated_at,
    last_seen_at,
    disabled_at
  )
  values (
    v_profile_id,
    v_endpoint,
    v_p256dh,
    v_auth,
    nullif(trim(coalesce(p_user_agent, '')), ''),
    true,
    now(),
    now(),
    null
  )
  on conflict (endpoint)
  do update set
    profile_id = excluded.profile_id,
    p256dh = excluded.p256dh,
    auth_key = excluded.auth_key,
    user_agent = excluded.user_agent,
    enabled = true,
    updated_at = now(),
    last_seen_at = now(),
    disabled_at = null;

  return true;
end;
$$;

revoke all
  on function public.register_push_subscription_v13(
    text,
    text,
    text,
    text
  )
  from public;

grant execute
  on function public.register_push_subscription_v13(
    text,
    text,
    text,
    text
  )
  to authenticated;

create or replace function public.disable_push_subscription_v13(
  p_endpoint text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile_id uuid;
begin
  v_profile_id := public.current_profile_id();

  if v_profile_id is null then
    raise exception 'Profile aktif untuk user login tidak ditemukan.';
  end if;

  update public.push_subscriptions_v13
  set
    enabled = false,
    updated_at = now(),
    disabled_at = now()
  where endpoint = trim(coalesce(p_endpoint, ''))
    and profile_id = v_profile_id;

  return found;
end;
$$;

revoke all
  on function public.disable_push_subscription_v13(text)
  from public;

grant execute
  on function public.disable_push_subscription_v13(text)
  to authenticated;

create or replace function public.kick_push_dispatch_v13(
  p_outbox_id bigint
)
returns void
language plpgsql
security definer
set search_path = public, net
as $$
declare
  v_url text;
  v_key text;
begin
  select
    nullif(trim(dispatch_url), ''),
    nullif(trim(dispatch_key), '')
  into
    v_url,
    v_key
  from public.push_dispatch_config_v13
  where singleton = true;

  if v_url is null or v_key is null then
    return;
  end if;

  begin
    perform net.http_post(
      url := v_url,
      headers := jsonb_build_object(
        'Content-Type',
        'application/json',
        'x-push-dispatch-key',
        v_key
      ),
      body := jsonb_build_object(
        'outboxId',
        p_outbox_id
      ),
      timeout_milliseconds := 5000
    );
  exception
    when others then
      update public.push_outbox_v13
      set last_error =
        left(
          'Dispatch kick gagal: ' || sqlerrm,
          2000
        )
      where id = p_outbox_id;
  end;
end;
$$;

revoke all
  on function public.kick_push_dispatch_v13(bigint)
  from public;

create or replace function public.enqueue_modern_push_v13()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_outbox_id bigint;
begin
  if new.recipient_profile_id is null then
    return new;
  end if;

  insert into public.push_outbox_v13 (
    source,
    source_id,
    recipient_profile_id,
    notification_type,
    module,
    title,
    message,
    link_path
  )
  values (
    'MODERN_NOTIFICATION',
    new.id::text,
    new.recipient_profile_id,
    new.notification_type,
    new.module,
    coalesce(nullif(trim(new.title), ''), 'Dashboard Marketing'),
    coalesce(nullif(trim(new.message), ''), 'Ada notifikasi baru.'),
    new.link_path
  )
  on conflict (
    source,
    source_id,
    recipient_profile_id
  )
  do nothing
  returning id into v_outbox_id;

  if v_outbox_id is not null then
    perform public.kick_push_dispatch_v13(
      v_outbox_id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enqueue_modern_push_v13
  on public.notifications;

create trigger trg_enqueue_modern_push_v13
after insert on public.notifications
for each row
execute function public.enqueue_modern_push_v13();

create or replace function public.enqueue_legacy_push_v13()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recipient_legacy_id text;
  v_recipient_profile_id uuid;
  v_outbox_id bigint;
begin
  if new.storage_key <> 'pertalife_notifications' then
    return new;
  end if;

  v_recipient_legacy_id :=
    trim(
      coalesce(
        new.payload->>'recipientUserId',
        ''
      )
    );

  if v_recipient_legacy_id = '' then
    return new;
  end if;

  select p.id
  into v_recipient_profile_id
  from public.profiles p
  where p.active = true
    and p.legacy_user_id =
      v_recipient_legacy_id
  limit 1;

  if v_recipient_profile_id is null then
    return new;
  end if;

  insert into public.push_outbox_v13 (
    source,
    source_id,
    recipient_profile_id,
    notification_type,
    module,
    title,
    message,
    link_path
  )
  values (
    'LEGACY_NOTIFICATION',
    new.entity_id,
    v_recipient_profile_id,
    'LEGACY_BELL',
    'LEGACY',
    coalesce(
      nullif(
        trim(new.payload->>'title'),
        ''
      ),
      'Dashboard Marketing'
    ),
    coalesce(
      nullif(
        trim(new.payload->>'message'),
        ''
      ),
      'Ada notifikasi baru.'
    ),
    nullif(
      trim(
        coalesce(
          new.payload->>'linkPath',
          ''
        )
      ),
      ''
    )
  )
  on conflict (
    source,
    source_id,
    recipient_profile_id
  )
  do nothing
  returning id into v_outbox_id;

  if v_outbox_id is not null then
    perform public.kick_push_dispatch_v13(
      v_outbox_id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_enqueue_legacy_push_v13
  on public.central_business_entities;

create trigger trg_enqueue_legacy_push_v13
after insert on public.central_business_entities
for each row
when (
  new.storage_key = 'pertalife_notifications'
)
execute function public.enqueue_legacy_push_v13();

commit;
