-- Dashboard Marketing — Comment V2 (schema-verified)
-- Verified against production schema on 2026-08-31.
-- Adds @mention, quote reply, comment/reply notifications, manager awareness,
-- exact-comment deep links, and activity-event based unseen state.
--
-- IMPORTANT:
-- - Existing add_activity_comment() and get_activity_detail() are preserved.
-- - Existing can_view_activity_id() / current_profile_id() remain the canonical
--   authorization source.
-- - This migration is additive and idempotent.

begin;

do $$
begin
  if to_regclass('public.activity_comments') is null then
    raise exception 'Table public.activity_comments tidak ditemukan';
  end if;

  if to_regclass('public.activities') is null then
    raise exception 'Table public.activities tidak ditemukan';
  end if;

  if to_regclass('public.notifications') is null then
    raise exception 'Table public.notifications tidak ditemukan';
  end if;

  if to_regclass('public.profiles') is null then
    raise exception 'Table public.profiles tidak ditemukan';
  end if;

  if to_regclass('public.activity_view_states') is null then
    raise exception 'Table public.activity_view_states tidak ditemukan';
  end if;

  if to_regclass('public.activity_collaborators') is null then
    raise exception 'Table public.activity_collaborators tidak ditemukan';
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 1) Quote reply
-- ---------------------------------------------------------------------------

alter table public.activity_comments
  add column if not exists parent_comment_id uuid null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'activity_comments_parent_comment_id_fkey'
      and conrelid = 'public.activity_comments'::regclass
  ) then
    alter table public.activity_comments
      add constraint activity_comments_parent_comment_id_fkey
      foreign key (parent_comment_id)
      references public.activity_comments(id)
      on delete set null;
  end if;
end
$$;

create index if not exists idx_activity_comments_parent_comment_id
  on public.activity_comments(parent_comment_id);

-- ---------------------------------------------------------------------------
-- 2) Structured @mentions
-- ---------------------------------------------------------------------------

create table if not exists public.activity_comment_mentions (
  comment_id uuid not null
    references public.activity_comments(id)
    on delete cascade,
  mentioned_profile_id uuid not null
    references public.profiles(id)
    on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, mentioned_profile_id)
);

create index if not exists idx_activity_comment_mentions_profile
  on public.activity_comment_mentions(mentioned_profile_id);

alter table public.activity_comment_mentions enable row level security;

grant select
  on public.activity_comment_mentions
  to authenticated;

drop policy if exists "activity_comment_mentions_select_visible"
  on public.activity_comment_mentions;

create policy "activity_comment_mentions_select_visible"
  on public.activity_comment_mentions
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.activity_comments c
      where c.id = activity_comment_mentions.comment_id
        and public.can_view_activity_id(c.activity_id)
    )
  );

-- ---------------------------------------------------------------------------
-- 3) Activity event stream
-- Card unseen state no longer depends on whether a bell notification exists.
-- ---------------------------------------------------------------------------

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  activity_id uuid not null
    references public.activities(id)
    on delete cascade,
  event_type text not null,
  actor_profile_id uuid null
    references public.profiles(id)
    on delete set null,
  source_id uuid null,
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_events_activity_created
  on public.activity_events(activity_id, created_at desc);

alter table public.activity_events enable row level security;

grant select
  on public.activity_events
  to authenticated;

drop policy if exists "activity_events_select_visible"
  on public.activity_events;

create policy "activity_events_select_visible"
  on public.activity_events
  for select
  to authenticated
  using (
    public.can_view_activity_id(activity_events.activity_id)
  );

create or replace function public.activity_event_actor_profile_id_v2()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select public.current_profile_id();
$$;

revoke all
  on function public.activity_event_actor_profile_id_v2()
  from public;

create or replace function public.log_activity_comment_event_v2()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.activity_events (
    activity_id,
    event_type,
    actor_profile_id,
    source_id
  )
  values (
    new.activity_id,
    case
      when new.parent_comment_id is null then 'COMMENT_ADDED'
      else 'COMMENT_REPLIED'
    end,
    public.activity_event_actor_profile_id_v2(),
    new.id
  );

  return new;
end;
$$;

drop trigger if exists trg_activity_comment_event_v2
  on public.activity_comments;

create trigger trg_activity_comment_event_v2
after insert on public.activity_comments
for each row
execute function public.log_activity_comment_event_v2();

create or replace function public.log_activity_update_event_v2()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Ignore an update that only touches updated_at.
  if (
    (to_jsonb(new) - 'updated_at')
    is distinct from
    (to_jsonb(old) - 'updated_at')
  ) then
    insert into public.activity_events (
      activity_id,
      event_type,
      actor_profile_id,
      source_id
    )
    values (
      new.id,
      'ACTIVITY_UPDATED',
      public.activity_event_actor_profile_id_v2(),
      new.id
    );
  end if;

  return new;
end;
$$;

drop trigger if exists trg_activity_update_event_v2
  on public.activities;

create trigger trg_activity_update_event_v2
after update on public.activities
for each row
execute function public.log_activity_update_event_v2();

create or replace function public.log_activity_related_event_v2()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_activity_id uuid;
  v_source_id uuid;
begin
  if tg_op = 'DELETE' then
    v_activity_id := old.activity_id;
    v_source_id := old.id;
  else
    v_activity_id := new.activity_id;
    v_source_id := new.id;
  end if;

  insert into public.activity_events (
    activity_id,
    event_type,
    actor_profile_id,
    source_id
  )
  values (
    v_activity_id,
    upper(tg_table_name || '_' || tg_op),
    public.activity_event_actor_profile_id_v2(),
    v_source_id
  );

  return coalesce(new, old);
end;
$$;

do $$
begin
  if to_regclass('public.activity_attachments') is not null then
    execute '
      drop trigger if exists trg_activity_attachment_event_v2
      on public.activity_attachments
    ';

    execute '
      create trigger trg_activity_attachment_event_v2
      after insert or delete on public.activity_attachments
      for each row
      execute function public.log_activity_related_event_v2()
    ';
  end if;
end
$$;

-- Server-side canonical unseen state.
create or replace function public.get_my_activity_attention_v2()
returns table (
  activity_id uuid,
  unseen_count integer,
  latest_event_at timestamptz,
  last_seen_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  with me as (
    select public.current_profile_id() as id
  )
  select
    e.activity_id,
    count(*)::integer as unseen_count,
    max(e.created_at) as latest_event_at,
    max(avs.last_seen_at) as last_seen_at
  from public.activity_events e
  cross join me
  left join public.activity_view_states avs
    on avs.activity_id = e.activity_id
   and avs.profile_id = me.id
  where
    me.id is not null
    and public.can_view_activity_id(e.activity_id)
    and e.actor_profile_id is distinct from me.id
    and e.created_at > coalesce(
      avs.last_seen_at,
      '1970-01-01 00:00:00+00'::timestamptz
    )
  group by e.activity_id;
$$;

revoke all
  on function public.get_my_activity_attention_v2()
  from public;

grant execute
  on function public.get_my_activity_attention_v2()
  to authenticated;

-- ---------------------------------------------------------------------------
-- 4) Discussion reader: existing activity access remains canonical.
-- ---------------------------------------------------------------------------

create or replace function public.get_activity_discussion_v2(
  p_activity_id uuid
)
returns table (
  id uuid,
  body text,
  created_by_profile_id uuid,
  author_name text,
  author_role text,
  author_unit text,
  author_department text,
  created_at timestamptz,
  parent_comment_id uuid,
  parent_author_name text,
  parent_body text,
  mentions jsonb
)
language sql
stable
security definer
set search_path = public
as $$
  select
    c.id,
    c.body,
    c.created_by_profile_id,
    p.full_name as author_name,
    p.role_level as author_role,
    p.unit as author_unit,
    p.department as author_department,
    c.created_at,
    c.parent_comment_id,
    pp.full_name as parent_author_name,
    pc.body as parent_body,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'profile_id', mp.id,
            'full_name', mp.full_name,
            'role_level', mp.role_level,
            'unit', mp.unit,
            'department', mp.department
          )
          order by mp.full_name
        )
        from public.activity_comment_mentions acm
        join public.profiles mp
          on mp.id = acm.mentioned_profile_id
        where acm.comment_id = c.id
      ),
      '[]'::jsonb
    ) as mentions
  from public.activity_comments c
  join public.profiles p
    on p.id = c.created_by_profile_id
  left join public.activity_comments pc
    on pc.id = c.parent_comment_id
  left join public.profiles pp
    on pp.id = pc.created_by_profile_id
  where c.activity_id = p_activity_id
    and public.current_profile_id() is not null
    and public.can_view_activity_id(p_activity_id)
  order by c.created_at asc;
$$;

revoke all
  on function public.get_activity_discussion_v2(uuid)
  from public;

grant execute
  on function public.get_activity_discussion_v2(uuid)
  to authenticated;

-- ---------------------------------------------------------------------------
-- 5) Decorate a comment created through existing add_activity_comment().
-- Existing comment authorization/history/legacy notification behavior stays.
-- ---------------------------------------------------------------------------

create or replace function public.decorate_activity_comment_v2(
  p_comment_id uuid,
  p_parent_comment_id uuid default null,
  p_mentioned_profile_ids uuid[] default '{}'::uuid[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_id uuid;
  v_actor_name text;
  v_activity_id uuid;
  v_activity_title text;
  v_owner_id uuid;
  v_owner_manager_id uuid;
  v_parent_author_id uuid;
  v_comment_created_at timestamptz;
  v_link text;
  v_target uuid;
  v_requested_count integer := 0;
  v_allowed_count integer := 0;
begin
  v_actor_id := public.current_profile_id();

  if v_actor_id is null then
    raise exception 'Profile aktif untuk user login tidak ditemukan.';
  end if;

  select p.full_name
    into v_actor_name
  from public.profiles p
  where p.id = v_actor_id;

  select
    c.activity_id,
    c.created_at,
    a.title,
    a.owner_profile_id
  into
    v_activity_id,
    v_comment_created_at,
    v_activity_title,
    v_owner_id
  from public.activity_comments c
  join public.activities a
    on a.id = c.activity_id
  where c.id = p_comment_id
    and c.created_by_profile_id = v_actor_id;

  if v_activity_id is null then
    raise exception
      'Komentar tidak ditemukan atau bukan milik user aktif.';
  end if;

  if not public.can_view_activity_id(v_activity_id) then
    raise exception
      'Anda tidak memiliki akses ke aktivitas ini.';
  end if;

  if p_parent_comment_id is not null then
    select pc.created_by_profile_id
      into v_parent_author_id
    from public.activity_comments pc
    where pc.id = p_parent_comment_id
      and pc.activity_id = v_activity_id;

    if v_parent_author_id is null then
      raise exception
        'Komentar parent tidak ditemukan pada aktivitas yang sama.';
    end if;

    update public.activity_comments
    set parent_comment_id = p_parent_comment_id
    where id = p_comment_id;

    -- The event was written at comment INSERT time, before parent metadata
    -- existed. Upgrade the semantic event after the reply is decorated.
    update public.activity_events
    set event_type = 'COMMENT_REPLIED'
    where activity_id = v_activity_id
      and source_id = p_comment_id
      and event_type = 'COMMENT_ADDED';
  end if;

  select p.manager_id
    into v_owner_manager_id
  from public.profiles p
  where p.id = v_owner_id;

  select count(distinct x.id)
    into v_requested_count
  from unnest(
    coalesce(
      p_mentioned_profile_ids,
      '{}'::uuid[]
    )
  ) as x(id)
  where x.id is distinct from v_actor_id;

  if v_requested_count > 0 then
    with recursive
    descendants(id) as (
      select p.id
      from public.profiles p
      where p.manager_id = v_actor_id
        and p.active = true

      union all

      select p.id
      from public.profiles p
      join descendants d
        on p.manager_id = d.id
      where p.active = true
    ),
    ancestors(id, manager_id) as (
      select p.id, p.manager_id
      from public.profiles p
      where p.id = (
        select me.manager_id
        from public.profiles me
        where me.id = v_actor_id
      )
        and p.active = true

      union all

      select p.id, p.manager_id
      from public.profiles p
      join ancestors a
        on p.id = a.manager_id
      where p.active = true
    ),
    special(id) as (
      select v_owner_id

      union
      select a.created_by_profile_id
      from public.activities a
      where a.id = v_activity_id

      union
      select a.validation_approver_profile_id
      from public.activities a
      where a.id = v_activity_id

      union
      select v_owner_manager_id

      union
      select v_parent_author_id

      union
      select c.profile_id
      from public.activity_collaborators c
      where c.activity_id = v_activity_id
    ),
    allowed(id) as (
      select id from descendants
      union
      select id from ancestors
      union
      select id from special
    )
    select count(distinct x.id)
      into v_allowed_count
    from unnest(
      coalesce(
        p_mentioned_profile_ids,
        '{}'::uuid[]
      )
    ) as x(id)
    join public.profiles p
      on p.id = x.id
     and p.active = true
    where
      x.id is distinct from v_actor_id
      and x.id in (
        select id
        from allowed
        where id is not null
      );

    if v_allowed_count <> v_requested_count then
      raise exception
        'Ada akun mention yang berada di luar hierarchy/participant yang diizinkan.';
    end if;
  end if;

  delete from public.activity_comment_mentions
  where comment_id = p_comment_id;

  insert into public.activity_comment_mentions (
    comment_id,
    mentioned_profile_id
  )
  select
    p_comment_id,
    x.id
  from (
    select distinct id
    from unnest(
      coalesce(
        p_mentioned_profile_ids,
        '{}'::uuid[]
      )
    ) as t(id)
  ) x
  where x.id is distinct from v_actor_id;

  v_link := format(
    '/aktivitas?task=%s&tab=discussion&comment=%s',
    v_activity_id,
    p_comment_id
  );

  -- Owner always receives discussion awareness, except the actor.
  if v_owner_id is not null
     and v_owner_id is distinct from v_actor_id then

    update public.notifications
    set link_path = v_link
    where id = (
      select n.id
      from public.notifications n
      where n.recipient_profile_id = v_owner_id
        and n.related_record_id = v_activity_id
        and n.notification_type = 'ACTIVITY_COMMENT'
        and n.created_at >= v_comment_created_at - interval '5 seconds'
      order by n.created_at desc
      limit 1
    );

    if not found then
      insert into public.notifications (
        recipient_profile_id,
        notification_type,
        module,
        title,
        message,
        related_record_id,
        link_path
      )
      values (
        v_owner_id,
        'ACTIVITY_COMMENT',
        'ACTIVITY',
        'Komentar baru pada aktivitas',
        format(
          '%s menambahkan komentar pada: %s',
          v_actor_name,
          v_activity_title
        ),
        v_activity_id,
        v_link
      );
    end if;
  end if;

  -- Explicit @mentions get highest notification priority.
  for v_target in
    select acm.mentioned_profile_id
    from public.activity_comment_mentions acm
    where acm.comment_id = p_comment_id
      and acm.mentioned_profile_id is distinct from v_actor_id
  loop
    update public.notifications
    set
      notification_type = 'ACTIVITY_MENTION',
      module = 'ACTIVITY',
      title = format(
        '%s menyebut Anda dalam komentar',
        v_actor_name
      ),
      message = format(
        'Anda di-mention pada: %s',
        v_activity_title
      ),
      link_path = v_link
    where id = (
      select n.id
      from public.notifications n
      where n.recipient_profile_id = v_target
        and n.related_record_id = v_activity_id
        and n.notification_type = 'ACTIVITY_COMMENT'
        and n.created_at >= v_comment_created_at - interval '5 seconds'
      order by n.created_at desc
      limit 1
    );

    if not found then
      insert into public.notifications (
        recipient_profile_id,
        notification_type,
        module,
        title,
        message,
        related_record_id,
        link_path
      )
      values (
        v_target,
        'ACTIVITY_MENTION',
        'ACTIVITY',
        format(
          '%s menyebut Anda dalam komentar',
          v_actor_name
        ),
        format(
          'Anda di-mention pada: %s',
          v_activity_title
        ),
        v_activity_id,
        v_link
      );
    end if;
  end loop;

  -- Parent author receives a reply notification, unless already mentioned.
  if v_parent_author_id is not null
     and v_parent_author_id is distinct from v_actor_id
     and not exists (
       select 1
       from public.activity_comment_mentions acm
       where acm.comment_id = p_comment_id
         and acm.mentioned_profile_id = v_parent_author_id
     ) then

    update public.notifications
    set
      notification_type = 'ACTIVITY_REPLY',
      module = 'ACTIVITY',
      title = 'Balasan komentar baru',
      message = format(
        '%s membalas komentar Anda pada: %s',
        v_actor_name,
        v_activity_title
      ),
      link_path = v_link
    where id = (
      select n.id
      from public.notifications n
      where n.recipient_profile_id = v_parent_author_id
        and n.related_record_id = v_activity_id
        and n.notification_type = 'ACTIVITY_COMMENT'
        and n.created_at >= v_comment_created_at - interval '5 seconds'
      order by n.created_at desc
      limit 1
    );

    if not found then
      insert into public.notifications (
        recipient_profile_id,
        notification_type,
        module,
        title,
        message,
        related_record_id,
        link_path
      )
      values (
        v_parent_author_id,
        'ACTIVITY_REPLY',
        'ACTIVITY',
        'Balasan komentar baru',
        format(
          '%s membalas komentar Anda pada: %s',
          v_actor_name,
          v_activity_title
        ),
        v_activity_id,
        v_link
      );
    end if;
  end if;

  -- Direct manager of the TASK OWNER sees every discussion update.
  -- This is the hierarchy-awareness rule that fixes the Banjar observer case.
  if v_owner_manager_id is not null
     and v_owner_manager_id is distinct from v_actor_id
     and not exists (
       select 1
       from public.activity_comment_mentions acm
       where acm.comment_id = p_comment_id
         and acm.mentioned_profile_id = v_owner_manager_id
     )
     and v_owner_manager_id is distinct from v_parent_author_id then

    update public.notifications
    set link_path = v_link
    where id = (
      select n.id
      from public.notifications n
      where n.recipient_profile_id = v_owner_manager_id
        and n.related_record_id = v_activity_id
        and n.notification_type in (
          'ACTIVITY_COMMENT',
          'ACTIVITY_COMMENT_MANAGER'
        )
        and n.created_at >= v_comment_created_at - interval '5 seconds'
      order by n.created_at desc
      limit 1
    );

    if not found then
      insert into public.notifications (
        recipient_profile_id,
        notification_type,
        module,
        title,
        message,
        related_record_id,
        link_path
      )
      values (
        v_owner_manager_id,
        'ACTIVITY_COMMENT_MANAGER',
        'ACTIVITY',
        'Update diskusi aktivitas tim',
        format(
          '%s menambahkan komentar pada: %s',
          v_actor_name,
          v_activity_title
        ),
        v_activity_id,
        v_link
      );
    end if;
  end if;
end;
$$;

revoke all
  on function public.decorate_activity_comment_v2(
    uuid,
    uuid,
    uuid[]
  )
  from public;

grant execute
  on function public.decorate_activity_comment_v2(
    uuid,
    uuid,
    uuid[]
  )
  to authenticated;

commit;

