-- Dashboard Marketing PertaLife
-- Tanda Terima V19 — end-to-end profile-native hardening
-- 2026-09-03
--
-- Goals:
-- 1. Make Document Handover permissions work with both legacy USR-* IDs and
--    profile-native PRF-<profile_uuid> runtime IDs.
-- 2. Allow Digital & Affinity / other Marketing Support profile-native users
--    to act only when they are an actual sender / receiver on a Tanda Terima.
-- 3. Make Tanda Terima audit records writable/viewable for the actual parties.
-- 4. Keep legacy pertalife_notifications as compatibility writes only, while
--    modern public.notifications becomes the user-facing Bell / Push source.
-- 5. Generate modern Tanda Terima notifications atomically from the committed
--    handover row, avoiding notification identity races.
-- 6. Allow DIKEMBALIKAN -> MENUNGGU PENERIMAAN for the same-TRM resend cycle.

begin;

create or replace function public.current_business_runtime_user_id_v19()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    nullif(trim(p.legacy_user_id), ''),
    'PRF-' || p.id::text
  )
  from public.profiles p
  where p.auth_user_id = auth.uid()
    and p.active = true
  limit 1;
$$;

revoke all
on function public.current_business_runtime_user_id_v19()
from public, anon;

grant execute
on function public.current_business_runtime_user_id_v19()
to authenticated;

create or replace function public.resolve_business_profile_id_v19(
  p_runtime_user_id text
)
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_value text := trim(coalesce(p_runtime_user_id, ''));
  v_profile_id uuid;
begin
  if v_value = '' then
    return null;
  end if;

  select p.id
  into v_profile_id
  from public.profiles p
  where p.active = true
    and upper(trim(coalesce(p.legacy_user_id, ''))) = upper(v_value)
  limit 1;

  if v_profile_id is not null then
    return v_profile_id;
  end if;

  if upper(v_value) like 'PRF-%' then
    select p.id
    into v_profile_id
    from public.profiles p
    where p.active = true
      and upper('PRF-' || p.id::text) = upper(v_value)
    limit 1;
  end if;

  return v_profile_id;
end;
$$;

revoke all
on function public.resolve_business_profile_id_v19(text)
from public, anon;

grant execute
on function public.resolve_business_profile_id_v19(text)
to authenticated;

create or replace function public.central_can_mutate_business_entity(
  p_storage_key text,
  p_new_payload jsonb,
  p_old_payload jsonb default null::jsonb
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_runtime_user_id text;
  v_relation text;
  v_sender text;
  v_receiver text;
  v_recipient text;
  v_payload jsonb := coalesce(p_new_payload, p_old_payload);
begin
  select p.*
  into v_profile
  from public.profiles p
  where p.auth_user_id = auth.uid()
    and p.active = true
  limit 1;

  if v_profile.id is null then
    return false;
  end if;

  if upper(trim(coalesce(v_profile.role_level, ''))) = 'SYSTEM_ADMIN' then
    return false;
  end if;

  v_runtime_user_id := upper(trim(coalesce(
    nullif(trim(v_profile.legacy_user_id), ''),
    'PRF-' || v_profile.id::text
  )));

  if upper(trim(coalesce(v_profile.legacy_user_id, ''))) = 'USR-000024' then
    return true;
  end if;

  -- Tanda Terima is party-based and must be checked before the generic
  -- Marketing Support subdivision deny rule.
  if p_storage_key = 'pertalife_document_handovers' then
    v_sender := upper(trim(coalesce(v_payload ->> 'senderUserId', '')));
    v_receiver := upper(trim(coalesce(v_payload ->> 'receiverUserId', '')));

    return v_runtime_user_id <> ''
      and v_runtime_user_id in (v_sender, v_receiver);
  end if;

  -- Tanda Terima audit compatibility rows: only the actor may create/update
  -- their own audit event. The central_business_audit table remains the
  -- authoritative immutable server audit generated by the RPC itself.
  if p_storage_key = 'pertalife_audit_logs'
     and upper(trim(coalesce(v_payload ->> 'module', ''))) = 'TANDA_TERIMA'
  then
    return upper(trim(coalesce(v_payload ->> 'userId', ''))) = v_runtime_user_id;
  end if;

  -- Legacy Tanda Terima notification rows are accepted only as compatibility
  -- writes. User-facing Bell/Push is generated from the committed handover by
  -- trg_notify_document_handover_v19 below.
  if p_storage_key = 'pertalife_notifications'
     and trim(coalesce(v_payload ->> 'linkPath', '')) = '/tanda-terima'
  then
    v_recipient := trim(coalesce(v_payload ->> 'recipientUserId', ''));
    return public.resolve_business_profile_id_v19(v_recipient) is not null;
  end if;

  if lower(trim(coalesce(v_profile.department, ''))) = 'marketing administration' then
    return p_storage_key = any(array[
      'pertalife_bookings',
      'pertalife_pipelines',
      'pertalife_appeals',
      'pertalife_productions',
      'pertalife_official_production_summaries',
      'pertalife_official_production_batches',
      'pertalife_official_policy_directory',
      'pertalife_service_documents',
      'pertalife_participants',
      'pertalife_historical',
      'pertalife_reimbursements',
      'pertalife_supporting_docs',
      'pertalife_approver_delegations',
      'pertalife_document_handovers',
      'pertalife_notifications',
      'pertalife_audit_logs'
    ]::text[]);
  end if;

  if lower(trim(coalesce(v_profile.department, ''))) = 'marketing communication' then
    return p_storage_key = any(array[
      'pertalife_marcomm_requests',
      'pertalife_marcomm_stock_transactions',
      'pertalife_marcomm_stock_opnames',
      'pertalife_service_documents',
      'pertalife_supporting_docs',
      'pertalife_approver_delegations',
      'pertalife_notifications',
      'pertalife_audit_logs'
    ]::text[]);
  end if;

  if lower(trim(coalesce(v_profile.unit, ''))) = 'marketing support' then
    return false;
  end if;

  v_relation := public.central_extract_relation_user_id(v_payload);

  if p_storage_key = 'pertalife_reimbursements' then
    v_relation := upper(trim(coalesce(v_payload ->> 'userId', v_relation)));
    return v_relation <> '' and public.central_user_id_in_current_scope(v_relation);
  end if;

  if p_storage_key = 'pertalife_marcomm_requests' then
    v_relation := upper(trim(coalesce(
      v_payload ->> 'requesterUserId',
      v_payload ->> 'requestedByUserId',
      v_payload ->> 'createdBy',
      v_relation
    )));
    return v_relation <> '' and public.central_user_id_in_current_scope(v_relation);
  end if;

  if p_storage_key = 'pertalife_notifications' then
    return true;
  end if;

  if p_storage_key = 'pertalife_audit_logs' then
    return true;
  end if;

  if p_storage_key = any(array[
    'pertalife_bookings',
    'pertalife_pipelines',
    'pertalife_appeals',
    'pertalife_service_documents',
    'pertalife_supporting_docs',
    'pertalife_activities',
    'pertalife_activity_comments'
  ]::text[]) then
    return v_relation <> '' and public.central_user_id_in_current_scope(v_relation);
  end if;

  return false;
end;
$$;

create or replace function public.central_can_view_business_entity(
  p_storage_key text,
  p_payload jsonb
)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_profile public.profiles%rowtype;
  v_runtime_user_id text;
  v_relation text;
  v_sender text;
  v_receiver text;
  v_recipient text;
  v_marketing_function text;
  v_record_id text;
begin
  select p.*
  into v_profile
  from public.profiles p
  where p.auth_user_id = auth.uid()
    and p.active = true
  limit 1;

  if v_profile.id is null then
    return false;
  end if;

  if upper(trim(coalesce(v_profile.role_level, ''))) = 'SYSTEM_ADMIN' then
    return false;
  end if;

  v_runtime_user_id := upper(trim(coalesce(
    nullif(trim(v_profile.legacy_user_id), ''),
    'PRF-' || v_profile.id::text
  )));

  -- From V19 onward Tanda Terima Bell/Push is modern public.notifications.
  -- Hide legacy compatibility rows so legacy users do not see duplicates.
  if p_storage_key = 'pertalife_notifications'
     and trim(coalesce(p_payload ->> 'linkPath', '')) = '/tanda-terima'
  then
    return false;
  end if;

  if upper(trim(coalesce(v_profile.legacy_user_id, ''))) = 'USR-000024' then
    return true;
  end if;

  if lower(trim(coalesce(v_profile.department, ''))) = 'marketing administration' then
    return p_storage_key = any(array[
      'pertalife_bookings',
      'pertalife_pipelines',
      'pertalife_appeals',
      'pertalife_productions',
      'pertalife_official_production_summaries',
      'pertalife_official_production_batches',
      'pertalife_official_policy_directory',
      'pertalife_service_documents',
      'pertalife_participants',
      'pertalife_historical',
      'pertalife_reimbursements',
      'pertalife_supporting_docs',
      'pertalife_approver_delegations',
      'pertalife_document_handovers',
      'pertalife_notifications'
    ]::text[]);
  end if;

  if lower(trim(coalesce(v_profile.department, ''))) = 'marketing communication' then
    return p_storage_key = any(array[
      'pertalife_marcomm_requests',
      'pertalife_marcomm_stock_transactions',
      'pertalife_marcomm_stock_opnames',
      'pertalife_service_documents',
      'pertalife_supporting_docs',
      'pertalife_approver_delegations',
      'pertalife_notifications'
    ]::text[]);
  end if;

  v_sender := upper(trim(coalesce(p_payload ->> 'senderUserId', '')));
  v_receiver := upper(trim(coalesce(p_payload ->> 'receiverUserId', '')));

  if p_storage_key = 'pertalife_document_handovers' then
    return v_runtime_user_id <> ''
      and v_runtime_user_id in (v_sender, v_receiver);
  end if;

  -- Tanda Terima audit history is visible only when the current runtime user is
  -- a party to the referenced registry. Marketing Administration broad users
  -- can still see operational handovers above, and party access applies here.
  if p_storage_key = 'pertalife_audit_logs'
     and upper(trim(coalesce(p_payload ->> 'module', ''))) = 'TANDA_TERIMA'
  then
    v_record_id := trim(coalesce(p_payload ->> 'recordId', ''));

    if v_record_id = '' then
      return false;
    end if;

    return exists (
      select 1
      from public.central_business_entities h
      where h.storage_key = 'pertalife_document_handovers'
        and h.entity_id = v_record_id
        and v_runtime_user_id in (
          upper(trim(coalesce(h.payload ->> 'senderUserId', ''))),
          upper(trim(coalesce(h.payload ->> 'receiverUserId', '')))
        )
    );
  end if;

  if lower(trim(coalesce(v_profile.unit, ''))) = 'marketing support' then
    return false;
  end if;

  if upper(trim(coalesce(v_profile.role_level, ''))) in ('DIRECTOR', 'ADVISOR')
     or (
       lower(trim(coalesce(v_profile.unit, ''))) = 'directorate marketing'
       and upper(trim(coalesce(v_profile.role_level, ''))) in ('DIRECTOR', 'ADVISOR')
     )
  then
    if p_storage_key = any(array[
      'pertalife_bookings',
      'pertalife_pipelines',
      'pertalife_appeals',
      'pertalife_productions',
      'pertalife_official_production_summaries',
      'pertalife_official_production_batches',
      'pertalife_official_policy_directory',
      'pertalife_historical'
    ]::text[]) then
      return true;
    end if;
  end if;

  v_relation := public.central_extract_relation_user_id(p_payload);
  v_recipient := upper(trim(coalesce(p_payload ->> 'recipientUserId', '')));
  v_marketing_function := lower(trim(coalesce(p_payload ->> 'marketingFunction', '')));

  if p_storage_key = 'pertalife_notifications' then
    return upper(trim(coalesce(v_profile.legacy_user_id, ''))) <> ''
      and v_recipient = upper(trim(coalesce(v_profile.legacy_user_id, '')));
  end if;

  if p_storage_key = 'pertalife_official_production_summaries'
     and v_relation = '' then
    if lower(trim(coalesce(v_profile.unit, ''))) = 'captive marketing' then
      return v_marketing_function = 'captive marketing';
    end if;

    if lower(trim(coalesce(v_profile.unit, ''))) = 'corporate & retail marketing' then
      return v_marketing_function = 'corporate & retail marketing';
    end if;
  end if;

  if v_relation <> '' and public.central_user_id_in_current_scope(v_relation) then
    return true;
  end if;

  if p_storage_key = 'pertalife_marcomm_requests' then
    v_relation := upper(trim(coalesce(
      p_payload ->> 'requesterUserId',
      p_payload ->> 'requestedByUserId',
      p_payload ->> 'createdBy',
      ''
    )));

    return v_relation <> ''
      and public.central_user_id_in_current_scope(v_relation);
  end if;

  return false;
end;
$$;

create or replace function public.central_validate_business_transition(
  p_storage_key text,
  p_old_payload jsonb,
  p_new_payload jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_status text := coalesce(p_old_payload ->> 'status', '');
  v_new_status text := coalesce(p_new_payload ->> 'status', '');
  v_old_cycle integer := coalesce(nullif(p_old_payload ->> 'cycleNumber', '')::integer, 1);
  v_new_cycle integer := coalesce(nullif(p_new_payload ->> 'cycleNumber', '')::integer, 1);
begin
  if jsonb_typeof(p_new_payload) <> 'object' then
    raise exception 'Payload harus berupa JSON object.';
  end if;

  if nullif(trim(coalesce(p_new_payload ->> 'id', '')), '') is null then
    raise exception 'ID record wajib tersedia.';
  end if;

  if p_storage_key = 'pertalife_bookings' then
    if v_new_status not in ('Submitted','Claimed','Approved','Rejected') then
      raise exception 'Status Booking tidak valid: %', v_new_status;
    end if;

    if p_old_payload is not null
       and v_old_status in ('Approved','Rejected')
       and v_new_status <> v_old_status then
      raise exception 'Booking terminal tidak dapat berpindah status lagi.';
    end if;
  end if;

  if p_storage_key = 'pertalife_pipelines' then
    if v_new_status not in (
      'Menunggu Upload Dokumen Marketing',
      'Dokumen Diajukan oleh Marketing',
      'On Progress Marketing Support',
      'Perlu Perbaikan Dokumen Marketing',
      'On Process Teknik',
      'Penawaran Telah Terbit',
      'Menunggu Feedback / Konfirmasi Klien',
      'Menunggu Upload Dokumen Closing',
      'Dokumen Closing Diajukan',
      'Dalam Verifikasi Marketing Support',
      'Menunggu Final Approval Team Leader Marketing Support',
      'WIN','LOSE'
    ) then
      raise exception 'Status Pipeline tidak valid: %', v_new_status;
    end if;

    if p_old_payload is not null
       and v_old_status = 'WIN'
       and v_new_status <> 'WIN' then
      raise exception 'Pipeline WIN bersifat final.';
    end if;

    if p_old_payload is not null
       and v_old_status = 'LOSE'
       and v_new_status <> 'LOSE'
       and not (
         public.central_is_target_support_root()
         or public.central_is_marketing_administration()
       ) then
      raise exception 'Reopen Pipeline LOSE hanya dapat dilakukan Marketing Support.';
    end if;
  end if;

  if p_storage_key = 'pertalife_productions' then
    if v_new_status not in ('Pending Checker','POSTED','Rejected') then
      raise exception 'Status Produksi tidak valid: %', v_new_status;
    end if;

    if p_old_payload is not null
       and v_old_status in ('POSTED','Rejected')
       and v_new_status <> v_old_status then
      raise exception 'Transaksi Produksi terminal tidak dapat diubah status.';
    end if;
  end if;

  if p_storage_key = 'pertalife_document_handovers' then
    if v_new_status not in (
      'MENUNGGU PENERIMAAN',
      'DITERIMA',
      'SELISIH DOKUMEN',
      'MENUNGGU KONFIRMASI PENGEMBALIAN',
      'DIKEMBALIKAN',
      'SELISIH PENGEMBALIAN',
      'DITOLAK',
      'DIBATALKAN'
    ) then
      raise exception 'Status Tanda Terima tidak valid: %', v_new_status;
    end if;

    if p_old_payload is not null
       and v_new_status <> v_old_status then

      if v_old_status = 'MENUNGGU PENERIMAAN'
         and v_new_status not in ('DITERIMA','SELISIH DOKUMEN','DITOLAK','DIBATALKAN') then
        raise exception 'Transisi Tanda Terima tidak valid: % -> %', v_old_status, v_new_status;
      end if;

      if v_old_status = 'DITERIMA'
         and v_new_status <> 'MENUNGGU KONFIRMASI PENGEMBALIAN' then
        raise exception 'Transisi Tanda Terima tidak valid: % -> %', v_old_status, v_new_status;
      end if;

      if v_old_status = 'SELISIH DOKUMEN'
         and v_new_status <> 'DITERIMA' then
        raise exception 'Transisi Tanda Terima tidak valid: % -> %', v_old_status, v_new_status;
      end if;

      if v_old_status = 'MENUNGGU KONFIRMASI PENGEMBALIAN'
         and v_new_status not in ('DIKEMBALIKAN','SELISIH PENGEMBALIAN') then
        raise exception 'Transisi Tanda Terima tidak valid: % -> %', v_old_status, v_new_status;
      end if;

      if v_old_status = 'SELISIH PENGEMBALIAN'
         and v_new_status <> 'DIKEMBALIKAN' then
        raise exception 'Transisi Tanda Terima tidak valid: % -> %', v_old_status, v_new_status;
      end if;

      -- V19: DIKEMBALIKAN is not terminal. It is the handoff point for the
      -- original sender to start a new cycle with the same TRM number.
      if v_old_status = 'DIKEMBALIKAN' then
        if v_new_status <> 'MENUNGGU PENERIMAAN' then
          raise exception 'Transisi Tanda Terima tidak valid: % -> %', v_old_status, v_new_status;
        end if;

        if v_new_cycle <= v_old_cycle then
          raise exception 'Kirim ulang wajib menaikkan cycleNumber Tanda Terima.';
        end if;
      end if;

      if v_old_status in ('DITOLAK','DIBATALKAN') then
        raise exception 'Tanda Terima terminal tidak dapat diubah.';
      end if;
    end if;
  end if;
end;
$$;

create or replace function public.notify_document_handover_v19()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_old_status text := case when tg_op = 'UPDATE' then coalesce(old.payload ->> 'status', '') else '' end;
  v_new_status text := coalesce(new.payload ->> 'status', '');
  v_cycle text := coalesce(nullif(new.payload ->> 'cycleNumber', ''), '1');
  v_recipient_runtime text;
  v_recipient_profile uuid;
  v_type text;
  v_title text;
  v_message text;
  v_dedupe text;
  v_sender_name text := coalesce(nullif(trim(new.payload ->> 'senderName'), ''), 'Pengirim');
  v_receiver_name text := coalesce(nullif(trim(new.payload ->> 'receiverName'), ''), 'Penerima');
  v_receipt_id text := new.entity_id;
begin
  if new.storage_key <> 'pertalife_document_handovers' then
    return new;
  end if;

  if coalesce((new.payload ->> 'externalReceiver')::boolean, false) then
    return new;
  end if;

  if tg_op = 'INSERT' then
    if v_new_status <> 'MENUNGGU PENERIMAAN' then
      return new;
    end if;

    v_recipient_runtime := new.payload ->> 'receiverUserId';
    v_type := 'TANDA_TERIMA_SUBMITTED';
    v_title := 'Dokumen Menunggu Penerimaan';
    v_message := v_sender_name || ' menyerahkan dokumen kepada Anda (' || v_receipt_id || ').';
    v_dedupe := 'trm:' || v_receipt_id || ':insert:c' || v_cycle;

  elsif v_old_status is distinct from v_new_status then
    if v_old_status = 'DIKEMBALIKAN' and v_new_status = 'MENUNGGU PENERIMAAN' then
      v_recipient_runtime := new.payload ->> 'receiverUserId';
      v_type := 'TANDA_TERIMA_RESUBMITTED';
      v_title := 'Dokumen Dikirim Ulang';
      v_message := v_sender_name || ' mengirim ulang dokumen untuk ' || v_receipt_id || '.';

    elsif v_old_status = 'MENUNGGU PENERIMAAN' and v_new_status = 'DITERIMA' then
      v_recipient_runtime := new.payload ->> 'senderUserId';
      v_type := 'TANDA_TERIMA_RECEIVED';
      v_title := 'Dokumen Telah Diterima';
      v_message := v_receiver_name || ' menerima dokumen ' || v_receipt_id || '.';

    elsif v_old_status = 'MENUNGGU PENERIMAAN' and v_new_status = 'SELISIH DOKUMEN' then
      v_recipient_runtime := new.payload ->> 'senderUserId';
      v_type := 'TANDA_TERIMA_DISCREPANCY';
      v_title := 'Selisih Dokumen Dilaporkan';
      v_message := v_receiver_name || ' melaporkan selisih pada ' || v_receipt_id || '.';

    elsif v_old_status = 'SELISIH DOKUMEN' and v_new_status = 'DITERIMA' then
      v_recipient_runtime := new.payload ->> 'senderUserId';
      v_type := 'TANDA_TERIMA_DISCREPANCY_RESOLVED';
      v_title := 'Selisih Dokumen Diselesaikan';
      v_message := 'Selisih dokumen pada ' || v_receipt_id || ' telah diselesaikan.';

    elsif v_old_status = 'MENUNGGU PENERIMAAN' and v_new_status = 'DITOLAK' then
      v_recipient_runtime := new.payload ->> 'senderUserId';
      v_type := 'TANDA_TERIMA_REJECTED';
      v_title := 'Penerimaan Dokumen Ditolak';
      v_message := v_receiver_name || ' menolak penerimaan ' || v_receipt_id || '.';

    elsif v_old_status = 'MENUNGGU PENERIMAAN' and v_new_status = 'DIBATALKAN' then
      v_recipient_runtime := new.payload ->> 'receiverUserId';
      v_type := 'TANDA_TERIMA_CANCELLED';
      v_title := 'Tanda Terima Dibatalkan';
      v_message := v_sender_name || ' membatalkan ' || v_receipt_id || '.';

    elsif v_old_status = 'DITERIMA' and v_new_status = 'MENUNGGU KONFIRMASI PENGEMBALIAN' then
      v_recipient_runtime := new.payload ->> 'senderUserId';
      v_type := 'TANDA_TERIMA_RETURN_SUBMITTED';
      v_title := 'Pengembalian Dokumen Menunggu Konfirmasi';
      v_message := v_receiver_name || ' mengembalikan dokumen untuk ' || v_receipt_id || '.';

    elsif v_old_status = 'MENUNGGU KONFIRMASI PENGEMBALIAN' and v_new_status = 'DIKEMBALIKAN' then
      v_recipient_runtime := new.payload ->> 'receiverUserId';
      v_type := 'TANDA_TERIMA_RETURN_CONFIRMED';
      v_title := 'Pengembalian Dokumen Dikonfirmasi';
      v_message := v_sender_name || ' mengonfirmasi penerimaan kembali ' || v_receipt_id || '.';

    elsif v_old_status = 'MENUNGGU KONFIRMASI PENGEMBALIAN' and v_new_status = 'SELISIH PENGEMBALIAN' then
      v_recipient_runtime := new.payload ->> 'receiverUserId';
      v_type := 'TANDA_TERIMA_RETURN_DISCREPANCY';
      v_title := 'Selisih Pengembalian Dilaporkan';
      v_message := v_sender_name || ' melaporkan selisih pengembalian pada ' || v_receipt_id || '.';

    elsif v_old_status = 'SELISIH PENGEMBALIAN' and v_new_status = 'DIKEMBALIKAN' then
      v_recipient_runtime := new.payload ->> 'receiverUserId';
      v_type := 'TANDA_TERIMA_RETURN_DISCREPANCY_RESOLVED';
      v_title := 'Selisih Pengembalian Diselesaikan';
      v_message := 'Selisih pengembalian pada ' || v_receipt_id || ' telah diselesaikan.';
    else
      return new;
    end if;

    v_dedupe := 'trm:' || v_receipt_id || ':' || lower(v_old_status) || '>' || lower(v_new_status) || ':c' || v_cycle;
  else
    return new;
  end if;

  v_recipient_profile := public.resolve_business_profile_id_v19(v_recipient_runtime);

  if v_recipient_profile is null then
    return new;
  end if;

  perform public.create_system_notification_vnext(
    v_recipient_profile,
    v_type,
    v_title,
    v_message,
    null,
    '/tanda-terima',
    'TANDA_TERIMA',
    v_dedupe,
    false
  );

  return new;
end;
$$;

drop trigger if exists trg_notify_document_handover_v19
on public.central_business_entities;

create trigger trg_notify_document_handover_v19
after insert or update
on public.central_business_entities
for each row
when (new.storage_key = 'pertalife_document_handovers')
execute function public.notify_document_handover_v19();

-- Avoid duplicate Push notifications from legacy compatibility notification
-- rows. Modern public.notifications is the sole Bell/Push source for Tanda
-- Terima after V19.
create or replace function public.enqueue_legacy_push_v13()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_recipient_legacy_id text;
  v_recipient_profile_id uuid;
  v_outbox_id bigint;
begin
  if new.storage_key <> 'pertalife_notifications' then
    return new;
  end if;

  if trim(coalesce(new.payload ->> 'linkPath', '')) = '/tanda-terima' then
    return new;
  end if;

  v_recipient_legacy_id := trim(coalesce(new.payload->>'recipientUserId', ''));

  if v_recipient_legacy_id = '' then
    return new;
  end if;

  select p.id
  into v_recipient_profile_id
  from public.profiles p
  where p.active = true
    and p.legacy_user_id = v_recipient_legacy_id
  limit 1;

  if v_recipient_profile_id is null then
    return new;
  end if;

  insert into public.push_outbox_v13 (
    source,
    source_id,
    recipient_profile_id,
    notification_type,
    module,
    title,
    message,
    link_path
  )
  values (
    'LEGACY_NOTIFICATION',
    new.entity_id,
    v_recipient_profile_id,
    'LEGACY_BELL',
    'LEGACY',
    coalesce(nullif(trim(new.payload->>'title'), ''), 'Dashboard Marketing'),
    coalesce(nullif(trim(new.payload->>'message'), ''), 'Ada notifikasi baru.'),
    nullif(trim(coalesce(new.payload->>'linkPath', '')), '')
  )
  on conflict (source, source_id, recipient_profile_id)
  do nothing
  returning id into v_outbox_id;

  if v_outbox_id is not null then
    perform public.kick_push_dispatch_v13(v_outbox_id);
  end if;

  return new;
end;
$$;

commit;
